# 04 - Data Preprocessing

## Objective

The objective of this notebook is to prepare the processed UAV network intrusion dataset for Machine Learning and Deep Learning model development.

The preprocessing pipeline includes:

- Removing non-informative features.
- Converting data into a model-compatible format.
- Encoding the target labels.
- Splitting the dataset into training and testing sets.
- Scaling numerical features where required.
- Saving the processed datasets for subsequent model development.

The resulting dataset will serve as the input for the Machine Learning and Deep Learning models developed in the following notebooks.

In [3]:
# Data Manipulation
import pandas as pd
import numpy as np

# Visualization (for verification if required)
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning Utilities
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# Display Settings
pd.set_option("display.max_columns", None)

In [4]:
# Load processed dataset
df = pd.read_csv("../data/interim/network_dataset.csv")

# Display first five rows
df.head()

,timestamp_c,frame.number,frame.len,frame.protocols,wlan.duration,wlan.ra,wlan.ta,wlan.da,wlan.sa,wlan.bssid,wlan.frag,wlan.seq,llc.type,ip.hdr_len,ip.len,ip.id,ip.flags,ip.ttl,ip.proto,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.seq_raw,tcp.ack_raw,tcp.hdr_len,tcp.flags,tcp.window_size,tcp.options,udp.srcport,udp.dstport,udp.length,data.data,data.len,wlan.fc.type,wlan.fc.subtype,time_since_last_packet,class
0,28105.97520,60.0,24.0,0,0,1,1,1,1,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00000,Benign
1,28105.97550,61.0,24.0,0,0,1,1,1,1,0,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00030,Benign
2,28107.09931,75.0,104.0,0,0,4,1,4,1,0,0,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,1.12381,Benign
3,28114.78570,122.0,86.0,2,44,1,0,1,0,0,0,14,2048,20,52,39340,64,128,6,2,4,62951,53,723862127,0,32,2,64240,1,0,0,0,0,0,2,8,7.68639,Benign
4,28114.88188,124.0,26.0,0,60,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,12,0.09618,Benign

In [5]:
print(f"Dataset Shape: {df.shape}")

Dataset Shape: (42258, 38)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42258 entries, 0 to 42257
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp_c             42258 non-null  float64
 1   frame.number            42258 non-null  float64
 2   frame.len               42258 non-null  float64
 3   frame.protocols         42258 non-null  int64
 4   wlan.duration           42258 non-null  int64
 5   wlan.ra                 42258 non-null  int64
 6   wlan.ta                 42258 non-null  int64
 7   wlan.da                 42258 non-null  int64
 8   wlan.sa                 42258 non-null  int64
 9   wlan.bssid              42258 non-null  int64
 10  wlan.frag               42258 non-null  int64
 11  wlan.seq                42258 non-null  int64
 12  llc.type                42258 non-null  int64
 13  ip.hdr_len              42258 non-null  int64
 14  ip.len                  42258 non-null  int64
 15  ip.id                   42258 non-null  int64
 16  ip.flags                42258 non-null  int64
 17  ip.ttl                  42258 non-null  int64
 18  ip.proto                42258 non-null  int64
 19  ip.src                  42258 non-null  int64
 20  ip.dst                  42258 non-null  int64
 21  tcp.srcport             42258 non-null  int64
 22  tcp.dstport             42258 non-null  int64
 23  tcp.seq_raw             42258 non-null  int64
 24  tcp.ack_raw             42258 non-null  int64
 25  tcp.hdr_len             42258 non-null  int64
 26  tcp.flags               42258 non-null  int64
 27  tcp.window_size         42258 non-null  int64
 28  tcp.options             42258 non-null  int64
 29  udp.srcport             42258 non-null  int64
 30  udp.dstport             42258 non-null  int64
 31  udp.length              42258 non-null  int64
 32  data.data               42258 non-null  int64
 33  data.len                42258 non-null  int64
 34  wlan.fc.type            42258 non-null  int64
 35  wlan.fc.subtype         42258 non-null  int64
 36  time_since_last_packet  42258 non-null  float64
 37  class                   42258 non-null  str
dtypes: float64(4), int64(33), str(1)
memory usage: 12.5 MB

## Removing Constant Features

Features with zero variance contain the same value across all observations and therefore do not contribute to distinguishing between different classes.

Such features do not provide useful information for Machine Learning or Deep Learning models and are removed to simplify the dataset while preserving its predictive capability.

In [7]:
# Identify constant features
constant_features = [
    col for col in df.columns
    if df[col].nunique() == 1
]
# Remove constant features
df.drop(columns=constant_features, inplace=True)

print(f"Updated Dataset Shape: {df.shape}")

Updated Dataset Shape: (42258, 36)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42258 entries, 0 to 42257
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp_c             42258 non-null  float64
 1   frame.number            42258 non-null  float64
 2   frame.len               42258 non-null  float64
 3   frame.protocols         42258 non-null  int64
 4   wlan.duration           42258 non-null  int64
 5   wlan.ra                 42258 non-null  int64
 6   wlan.ta                 42258 non-null  int64
 7   wlan.da                 42258 non-null  int64
 8   wlan.sa                 42258 non-null  int64
 9   wlan.bssid              42258 non-null  int64
 10  wlan.seq                42258 non-null  int64
 11  llc.type                42258 non-null  int64
 12  ip.hdr_len              42258 non-null  int64
 13  ip.len                  42258 non-null  int64
 14  ip.id                   42258 non-null  int64
 15  ip.flags                42258 non-null  int64
 16  ip.ttl                  42258 non-null  int64
 17  ip.proto                42258 non-null  int64
 18  ip.src                  42258 non-null  int64
 19  ip.dst                  42258 non-null  int64
 20  tcp.srcport             42258 non-null  int64
 21  tcp.dstport             42258 non-null  int64
 22  tcp.seq_raw             42258 non-null  int64
 23  tcp.hdr_len             42258 non-null  int64
 24  tcp.flags               42258 non-null  int64
 25  tcp.window_size         42258 non-null  int64
 26  tcp.options             42258 non-null  int64
 27  udp.srcport             42258 non-null  int64
 28  udp.dstport             42258 non-null  int64
 29  udp.length              42258 non-null  int64
 30  data.data               42258 non-null  int64
 31  data.len                42258 non-null  int64
 32  wlan.fc.type            42258 non-null  int64
 33  wlan.fc.subtype         42258 non-null  int64
 34  time_since_last_packet  42258 non-null  float64
 35  class                   42258 non-null  str
dtypes: float64(4), int64(31), str(1)
memory usage: 11.8 MB

In [9]:
# Features to remove
irrelevant_features = [
    "frame.number",
    "timestamp_c"
]

# Drop the features
df.drop(columns=irrelevant_features, inplace=True)

print("Removed Features:")
print(irrelevant_features)

print(f"\nUpdated Dataset Shape: {df.shape}")

Removed Features:
['frame.number', 'timestamp_c']

Updated Dataset Shape: (42258, 34)

## Observation

Two metadata-related features (`frame.number` and `timestamp_c`) were removed from the dataset.

These features describe the packet capture process rather than the characteristics of network traffic itself. Removing them helps prevent the model from learning dataset-specific ordering or timing information while preserving meaningful temporal behavior through the `time_since_last_packet` feature.

In [10]:
# Keep protocol sequence/identifier features (wlan.seq, ip.id, tcp.seq_raw);
# evaluate their usefulness later during feature engineering.

# Target Label Encoding

The target variable contains categorical attack labels represented as text.

Since Machine Learning algorithms require numerical target values, the class labels are converted into integer representations using **LabelEncoder**.

The label mapping is displayed and recorded to ensure consistency during model training and evaluation.

In [11]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Encode target labels
df["class"] = label_encoder.fit_transform(df["class"])

In [12]:
# Display label mapping
label_mapping = dict(zip(label_encoder.classes_,
                         label_encoder.transform(label_encoder.classes_)))

print("Label Encoding Mapping:")
print(label_mapping)

Label Encoding Mapping:
{'Benign': np.int64(0), 'DoS': np.int64(1), 'Evil Twin': np.int64(2), 'FDI': np.int64(3), 'Replay': np.int64(4)}

In [13]:
df.head()

,frame.len,frame.protocols,wlan.duration,wlan.ra,wlan.ta,wlan.da,wlan.sa,wlan.bssid,wlan.seq,llc.type,ip.hdr_len,ip.len,ip.id,ip.flags,ip.ttl,ip.proto,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.seq_raw,tcp.hdr_len,tcp.flags,tcp.window_size,tcp.options,udp.srcport,udp.dstport,udp.length,data.data,data.len,wlan.fc.type,wlan.fc.subtype,time_since_last_packet,class
0,24.0,0,0,1,1,1,1,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00000,0
1,24.0,0,0,1,1,1,1,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00030,0
2,104.0,0,0,4,1,4,1,0,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,1.12381,0
3,86.0,2,44,1,0,1,0,0,14,2048,20,52,39340,64,128,6,2,4,62951,53,723862127,32,2,64240,1,0,0,0,0,0,2,8,7.68639,0
4,26.0,0,60,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,12,0.09618,0

## Feature–Target Separation

The dataset is divided into:

- **Feature Matrix (X):** Contains all input variables used for model training.
- **Target Vector (y):** Contains the encoded attack labels.

Separating the features and target variable is a standard preprocessing step before model training and evaluation.

In [14]:
# Separate input features and target label

X = df.drop(columns=["class"])
y = df["class"]

print(f"Feature Matrix Shape : {X.shape}")
print(f"Target Vector Shape  : {y.shape}")

Feature Matrix Shape : (42258, 33)
Target Vector Shape  : (42258,)

In [15]:
X.head()

,frame.len,frame.protocols,wlan.duration,wlan.ra,wlan.ta,wlan.da,wlan.sa,wlan.bssid,wlan.seq,llc.type,ip.hdr_len,ip.len,ip.id,ip.flags,ip.ttl,ip.proto,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.seq_raw,tcp.hdr_len,tcp.flags,tcp.window_size,tcp.options,udp.srcport,udp.dstport,udp.length,data.data,data.len,wlan.fc.type,wlan.fc.subtype,time_since_last_packet
0,24.0,0,0,1,1,1,1,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00000
1,24.0,0,0,1,1,1,1,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,4,0.00030
2,104.0,0,0,4,1,4,1,0,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,1.12381
3,86.0,2,44,1,0,1,0,0,14,2048,20,52,39340,64,128,6,2,4,62951,53,723862127,32,2,64240,1,0,0,0,0,0,2,8,7.68639
4,26.0,0,60,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,12,0.09618

In [16]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

## Observation

The dataset has been successfully separated into input features and target labels.

- The feature matrix contains **32 predictive features**.
- The target vector contains the encoded attack classes.

This separation prepares the dataset for train-test splitting and subsequent model development.

The dataset is divided into separate training and testing sets.

- The **training set** is used to learn the relationship between network features and attack classes.
- The **testing set** is kept completely unseen during training and is used to evaluate model performance.

A **stratified split** is used to preserve the original class distribution in both subsets, ensuring a fair evaluation.

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (33806, 33)
Testing Features  : (8452, 33)
Training Labels   : (33806,)
Testing Labels    : (8452,)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns
)

X_test = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns
)

In [20]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(scaler, "../models/scaler.pkl")

print("✅ Scaler saved successfully!")

✅ Scaler saved successfully!

In [21]:
print("Training Class Distribution")
print(y_train.value_counts(normalize=True))

print("\nTesting Class Distribution")
print(y_test.value_counts(normalize=True))

Training Class Distribution
class
4    0.284121
1    0.276194
0    0.223037
2    0.134473
3    0.082175
Name: proportion, dtype: float64

Testing Class Distribution
class
4    0.284075
1    0.276148
0    0.223024
2    0.134524
3    0.082229
Name: proportion, dtype: float64

Since our dataset contains multiple attack classes, a random split could accidentally produce unequal class distributions in the training and testing sets. Using stratification preserves the original class proportions, leading to a more reliable and unbiased evaluation of the intrusion detection models.

In [22]:
from pathlib import Path

Path("../data/processed").mkdir(parents=True, exist_ok=True)

In [23]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

In [24]:
import os

os.listdir("../data/processed")

['X_test.csv', 'X_train.csv', 'y_test.csv', 'y_train.csv']

### Observation

The processed dataset has been successfully saved for downstream machine learning experiments. Subsequent notebooks will directly load these files, ensuring a consistent preprocessing pipeline across all models.

In [26]:
import os

os.makedirs("../sample_data", exist_ok=True)

sample_df = X.sample(
    n=300,
    random_state=42
)

sample_df.to_csv(
    "../sample_data/sample_uav_traffic.csv",
    index=False
)

print("✅ Sample deployment dataset created!")
print(sample_df.shape)

✅ Sample deployment dataset created!
(300, 33)

In [28]:
X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

In [29]:
mixed = pd.concat([
    X_test[y_test == 0].sample(15, random_state=1),
    X_test[y_test == 1].sample(15, random_state=2),
    X_test[y_test == 2].sample(15, random_state=3),
])

mixed = mixed.sample(frac=1, random_state=42)
mixed.to_csv("../sample_data/mixed_sample.csv", index=False)

In [30]:
import pandas as pd
import os

os.makedirs("../sample_data", exist_ok=True)

# Reset indices
X = X_test.reset_index(drop=True)
y = y_test.reset_index(drop=True)

# -----------------------------
# Capture Session 01
# Mostly Benign
# -----------------------------

capture_01 = pd.concat([
    X[y == 0].sample(45, random_state=11),
    X[y != 0].sample(5, random_state=12)
]).sample(frac=1, random_state=13)

capture_01.to_csv("../sample_data/capture_session_01.csv", index=False)


# -----------------------------
# Capture Session 02
# Balanced traffic
# -----------------------------

capture_02 = pd.concat([
    X[y == 0].sample(28, random_state=21),
    X[y != 0].sample(22, random_state=22)
]).sample(frac=1, random_state=23)

capture_02.to_csv("../sample_data/capture_session_02.csv", index=False)


# -----------------------------
# Capture Session 03
# Attack dominated
# -----------------------------

capture_03 = pd.concat([
    X[y == 0].sample(8, random_state=31),
    X[y != 0].sample(42, random_state=32)
]).sample(frac=1, random_state=33)

capture_03.to_csv("../sample_data/capture_session_03.csv", index=False)

print("✅ Sample capture files created successfully.")

✅ Sample capture files created successfully.

In [32]:
print("Capture 01")
print(y[capture_01.index].value_counts())

print("\nCapture 02")
print(y[capture_02.index].value_counts())

print("\nCapture 03")
print(y[capture_03.index].value_counts())

Capture 01
class
0    45
2     3
1     2
Name: count, dtype: int64

Capture 02
class
0    28
1     8
4     7
2     4
3     3
Name: count, dtype: int64

Capture 03
class
4    18
1    15
0     8
2     5
3     4
Name: count, dtype: int64

In [34]:
import joblib
import pandas as pd

model = joblib.load("../models/xgboost_final.pkl")
scaler = joblib.load("../models/scaler.pkl")

label_map = {
    0: "Benign",
    1: "DoS Attack",
    2: "Replay",
    3: "Evil Twin",
    4: "False Data Injection"
}

for file in [
    "../sample_data/capture_session_01.csv",
    "../sample_data/capture_session_02.csv",
    "../sample_data/capture_session_03.csv"
]:

    df = pd.read_csv(file)

    X = scaler.transform(df)

    pred = model.predict(X)

    pred = pd.Series(pred).map(label_map)

    print(file)
    print(pred.value_counts())
    print("-"*50)

../sample_data/capture_session_01.csv
Evil Twin               47
False Data Injection     3
Name: count, dtype: int64
--------------------------------------------------
../sample_data/capture_session_02.csv
Evil Twin               44
False Data Injection     6
Name: count, dtype: int64
--------------------------------------------------
../sample_data/capture_session_03.csv
Evil Twin               39
False Data Injection    11
Name: count, dtype: int64
--------------------------------------------------

In [35]:
print(model.feature_names_in_)

['frame.len' 'frame.protocols' 'wlan.duration' 'wlan.ra' 'wlan.ta'
 'wlan.da' 'wlan.sa' 'wlan.bssid' 'wlan.seq' 'llc.type' 'ip.hdr_len'
 'ip.len' 'ip.id' 'ip.flags' 'ip.ttl' 'ip.proto' 'ip.src' 'ip.dst'
 'tcp.srcport' 'tcp.dstport' 'tcp.seq_raw' 'tcp.hdr_len' 'tcp.flags'
 'tcp.window_size' 'tcp.options' 'udp.srcport' 'udp.dstport' 'udp.length'
 'data.data' 'data.len' 'wlan.fc.type' 'wlan.fc.subtype'
 'time_since_last_packet']